name: base_x
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/litaoh/base-x

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  hex: ^0.1.2
  pedantic: ^1.8.0
  test: ^1.6.0
